### ISSUE TITLE
Front end stack install steps

### ISSUE THREAD

**Issue by bradallenfisher** [elmsln/elmsln#1342]
@heyMP maybe you could shed some light on this.

Here are the steps I have taken to install gulp and bower. I am getting some errors and can't run gulp.
Here is what I have been doing.
```shell
#!/bin/bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
source ~/.bashrc
nvm install 6.7
source ~/.bashrc
cd /var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app
npm install gulp
npm install bower
npm install
bower install
```
Here is an example error when I try to install 

```shell
npm install gulp
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> gifsicle@3.0.4 postinstall /var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/gifsicle
> node lib/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm WARN install:gifsicle@3.0.4 gifsicle@3.0.4 postinstall: `node lib/install.js`
npm WARN install:gifsicle@3.0.4 Exit status 1

> jpegtran-bin@3.1.0 postinstall /var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/jpegtran-bin
> node lib/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm WARN install:jpegtran-bin@3.1.0 jpegtran-bin@3.1.0 postinstall: `node lib/install.js`
npm WARN install:jpegtran-bin@3.1.0 Exit status 1

> optipng-bin@3.1.2 postinstall /var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/optipng-bin
> node lib/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm WARN install:optipng-bin@3.1.2 optipng-bin@3.1.2 postinstall: `node lib/install.js`
npm WARN install:optipng-bin@3.1.2 Exit status 1
heymp@0.0.0 /var/www/elmsln/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/app
└── gulp@3.9.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN heymp@0.0.0 No repository field.
npm WARN heymp@0.0.0 No license field.
```

**Comment by btopro** [comment]
Add to docs
