### ISSUE TITLE
hit back button in browser to studio = bug

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#1752]
occasionally when I go back to the studio app from another page using the back button I generate the following:

```
EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'dmd201'
Error: Cannot match any routes. URL Segment: 'dmd201'
    at ApplyRedirects.noMatchError (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:1484417)
    at CatchSubscriber.selector (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:1483791)
    at CatchSubscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:647855)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at LastSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
ErrorHandler.handleError @ vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2
vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2
vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2 Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'dmd201'
Error: Cannot match any routes. URL Segment: 'dmd201'
    at ApplyRedirects.noMatchError (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.selector (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at LastSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at resolvePromise (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at resolvePromise (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5
    at ZoneDelegate.invokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at Object.onInvokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at ZoneDelegate.invokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at Zone.runTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at drainMicroTaskQueue (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
ErrorHandler.handleError @ vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2
vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5 Unhandled Promise rejection: Cannot match any routes. URL Segment: 'dmd201' ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot match any routes. URL Segment: 'dmd201'
    at ApplyRedirects.noMatchError (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.selector (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at LastSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1) Error: Cannot match any routes. URL Segment: 'dmd201'
    at ApplyRedirects.noMatchError (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:1484417)
    at CatchSubscriber.selector (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:1483791)
    at CatchSubscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2:647855)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at MapSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
    at MapSubscriber.Subscriber.error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:19829)
    at LastSubscriber.Subscriber._error (https://studio.aanda.psu.edu/dmd201/profiles/cle__2/modules/features/cle_app/app/dist/vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1:20208)
consoleError @ vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5
vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5 Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'dmd201'
Error: Cannot match any routes. URL Segment: 'dmd201'
    at ApplyRedirects.noMatchError (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.selector (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at LastSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at ApplyRedirects.noMatchError (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.selector (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at CatchSubscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at MapSubscriber.Subscriber.error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at LastSubscriber.Subscriber._error (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:1)
    at resolvePromise (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at resolvePromise (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5
    at ZoneDelegate.invokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at Object.onInvokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:2)
    at ZoneDelegate.invokeTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at Zone.runTask (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
    at drainMicroTaskQueue (vendor.bundle.js,qojzree.pagespeed.jm.Pwi1ajXQRy.js:5)
```

**Comment by btopro** [comment]
#1766 duplicate
